<!DOCTYPE HTML>
<html>
<head>
<title>融和贷--seo系统</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
 <!-- Bootstrap Core CSS -->
<link href="/zixun/css/backend/bootstrap.min.css" rel='stylesheet' type='text/css' />
<!-- Custom CSS -->
<link href="/zixun/css/backend/style.css" rel='stylesheet' type='text/css' />
<!-- Graph CSS -->
<link href="/zixun/css/backend/lines.css" rel='stylesheet' type='text/css' />
<link href="/zixun/css/backend/font-awesome.css" rel="stylesheet"> 
<!-- jQuery -->
<script src="/zixun/js/backend/jquery.min.js"></script>
<!----webfonts--->
<link href='../css/backend/css.css' rel='stylesheet' type='text/css'>
<!---//webfonts--->  
<!-- Nav CSS -->
<link href="/zixun/css/backend/custom.css" rel="stylesheet">
<!-- Metis Menu Plugin JavaScript -->
<script src="/zixun/js/backend/metisMenu.min.js"></script>
<script src="/zixun/js/backend/custom.js"></script>
<!-- Graph JavaScript -->
<script src="/zixun/js/backend/d3.v3.js"></script>
<script src="/zixun/js/backend/rickshaw.js"></script>
</head>
<body>
<div id="wrapper">
     <!-- Navigation -->
        <nav class="top1 navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <a class="navbar-brand" href="../backendrhd/home">融和贷-seo系统</a>
            </div>
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="#"><i class="fa fa-laptop nav_icon"></i>管理员<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="/zixun/backendrhd/adduser">添加管理员</a>
                                </li>
                                <li>
                                    <a href="/zixun/backendrhd/userlist">所有管理员</a>
                                </li>
                                <li>
                                    <a href="/zixun/backendrhd/LoginOut">退出登录</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-indent nav_icon"></i>栏目分类管理<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="/zixun/backendrhd/addcolumn">添加栏目</a>
                                </li>
                                <li>
                                    <a href="/zixun/backendrhd/columnlist">栏目管理</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-envelope nav_icon"></i>文章管理<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="/zixun/backendrhd/addarticles">添加文章</a>
                                </li>
                                <li>
                                    <a href="/zixun/backendrhd/articleslist">文章列表</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-envelope nav_icon"></i>友链管理<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="/zixun/backendrhd/addlinks">添加友链</a>
                                </li>
                                <li>
                                    <a href="/zixun/backendrhd/linkslist">友链列表</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-envelope nav_icon"></i>URL跳转管理<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="/zixun/backendrhd/addurls">添加URL跳转</a>
                                </li>
                                <li>
                                    <a href="/zixun/backendrhd/urlslist">URL跳转列表</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper" >

                    <?php echo $this->getContent(); ?>

            <!-- /#page-wrapper -->
        </div>
    <!-- /#wrapper -->
    <!-- Bootstrap Core JavaScript -->
    <script src="/zixun/js/backend/bootstrap.min.js"></script>
</body>
</html>