<div class="monument2 clearbb">
    <div class="monumentit">当前位置:<a href="http://www.ronghedai.com/">融和贷</a>>
    <a href="./<?=$this->view->category['parent']->url?>/"><?=$this->view->category['parent']->name?></a>><a href="./<?=$this->view->category['category']->url?>/"><?=$this->view->category['category']->name?></a></div>
    <div class="monument2_s1">
        <div class="basep_cont1 borderside">
            <div class="basep_cont1c1">
                <h1><?=$article->name?></h1>
                <p class="basep_cont1c1t"><span>时间：<?=date('Y/m/d  h:i:s', $article->add_time)?></span><span>来源：<?=$article->source1?></span><span>点击数：<?=$article->click_total?></span></p>
                <div class="basep_cont1c1p">
                    <?=htmlspecialchars_decode($article->content)?>
                </div>
            </div>

            <div class="basep_cont1c2">
                <div class="bdsharebuttonbox" style="margin-top: 44px;margin-bottom: 18px;">
                    <a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间">QQ空间</a>
                    <a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博">新浪微博</a>
                    <a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博">腾讯微博</a>
                    <a href="#" class="bds_renren" data-cmd="renren" title="分享到人人网">人人网</a>
                    <a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信">微信</a>
                    <a href="#" class="bds_more" data-cmd="more">分享到：</a>
                </div>
                <p>上一篇：
                    <?php
                        $before = Articles::findFirst(array('second_category_id='.$article->second_category_id.' and id <'.$article->id));
                    if ($before == false) {
                        echo '暂无信息';
                    } else {
                        echo '<a href="./show_'.$before->id.'">'.$before->name.'</a>';
                    }
                    ?>

                </p>
                <p>下一篇：
                    <?php
                    $before = Articles::findFirst(array('second_category_id='.$article->second_category_id.' and id >'.$article->id));
                    if ($before == false) {
                        echo '暂无信息';
                    } else {
                        echo '<a href="./show_'.$before->id.'">'.$before->name.'</a>';
                    }
                    ?>
                </p>
            </div>

        </div>

        <div class="basep_cont2 borderside">
            <h4 class="jc_ticon"><?=$this->view->category['category']->name?> 相关推荐</h4>
            <div class="basep_cont2s clearbb">
                <ul class="clearbb">
                    <?php
                    foreach (Articles::find(array('id <'.$article->id.'  and second_category_id='.$category['category']->id, 'columns'=>'id,name', 'order'=> 'id desc', 'limit'=>12)) as $item) {
                        ?>
                        <li>
                            <a href="./show_<?=$item->id?>" target="_blank" ><?=$item->name?></a>
                        </li>
                        <?php
                    }
                    ?>

                </ul>

            </div>
        </div>

    </div>

    <div class="monument2_s2">
        <div class="monument2_s2c1 borderside">
            <h4 class="jc_ticon"><?=$this->view->category['category']->name?> 热文推荐</h4>
            <ul>
                <?php
                foreach (Articles::find(array('second_category_id='.$category['category']->id, 'columns'=>'id,name', 'order'=> 'click_total desc', 'limit'=>8)) as $item) {
                    ?>
                    <li>
                        <a href="./show_<?=$item->id?>" target="_blank" ><?=$item->name?></a>
                    </li>
                    <?php
                }
                ?>
            </ul>
        </div>
        <a href="http://www.ronghedai.com/?user&q=get_share_ajax&alias=drawreg&active_reg=seo_reg" target="_blank"><div class="monument2_s2c2"></div></a>
        <div class="monument2_s2c1 borderside" style="margin-bottom: 20px;">
            <h4 class="jc_ticon"><?=$this->view->category['parent']->name?> 最新文章</h4>
            <ul>
                <?php
                foreach (Articles::find(array('first_category_id='.$category['parent']->id, 'columns'=>'id,name', 'order'=> 'id desc', 'limit'=>8)) as $item) {
                    ?>
                    <li>
                        <a href="./show_<?=$item->id?>" target="_blank" ><?=$item->name?></a>
                    </li>
                    <?php
                }
                ?>
            </ul>
        </div>
        <div class="monument2_s2c3 clearbb">
            <dl>
                <dt></dt>
                <dd>
                    <h5>立扫二维码</h5>
                    <p>注册即享</p>
                    <p>688现金好礼</p>
                </dd>
            </dl>
        </div>
        <div class="monument2_s2c3 clearbb" id="monument2_s2c3id">
            <dl>
                <dt></dt>
                <dd>
                    <h5>下载APP</h5>
                    <p>融和贷理财app</p>
                    <p>随身财富 触手可及</p>
                </dd>
            </dl>
        </div>
    </div>

</div>

<div class="monument1" id="monument1id" style="margin-top: 0px;">

</div>

<div class="monument3 borderside">
    <h4 class="jc_ticon">相关主题</h4>
    <ul class="clearbb"  id="monument3c">
        <?php
        foreach (Category::find(array('parent_id=0','columns'=>'name,url')) as $item) {
            ?>
            <li>
                <a href="./<?=$item->url?>/" ><?=$item->name?></a>
            </li>
            <?php
        }
        ?>
    </ul>
</div>

<div  class="monument5son borderside">
    <h4 class="jc_ticon">热门推荐</h4>
    <ul class="clearbb">
        <?php
        foreach (Category::find(array('parent_id='.$this->view->category['parent']->id.' and id<>'.$this->view->category['category']->id,'columns'=>'name,url', 'order'=> ' RAND() ', 'limit'=>10)) as $item) {
            ?>
            <li><a href="./<?=$item->url?>/"><?=$item->name?></a></li>
            <?php
        }
        ?>
    </ul>
</div>
<script>
    $(function(){
        $('#monument3c li:last').css('margin-right','0px');
    })

</script>
<script>
    window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdMiniList":false,"bdPic":"","bdStyle":"1","bdSize":"24"},"share":{"bdSize":16},"selectShare":{"bdContainerClass":null,"bdSelectMiniList":["qzone","tsina","tqq","renren","weixin"]}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];
</script>
<?php
$article->content = htmlspecialchars_decode($article->content);
$article->click_total= $article->click_total+1;
$article->first_category_id = $article->first_category_id.'-'.$article->second_category_id;
$article->save();
?>