<div class="monument2 clearbb">
    <div class="monumentit">当前位置:<a href="http://www.ronghedai.com/" target="_blank">融和贷</a>><a href="../<?=$this->view->category['parent']->url?>/"><?=$this->view->category['parent']->name?></a>><a href="../<?=$this->view->category['category']->url?>/"><?=$this->view->category['category']->name?></a></div>
    <div class="monument2_s1">
        <div class="knowledge_cont borderside">
            <h4 class="jc_ticon"><?=$this->view->category['category']->name?>  列表页</h4>
            <div class="knowledge_cont1">
                <?php
                    foreach ($pages->items as $item) {
                        ?>
                        <dl>
                            <dt><a href="../show_<?=$item->id?>" ><?=$item->name?></a></dt>
                            <dd>
                                <p>
                                    <?=mb_substr( strip_tags(htmlspecialchars_decode($item->content)), 0, 60, 'utf-8')?>……
                                    <a href="../show_<?=$item->id?>" >【详情】</a></p>
                                <div class="knowled_c"><span><?=date('Y-m-d  h:i:s', $item->add_time)?></span><i><?=$item->click_total?></i></div>
                            </dd>
                        </dl>
                        <?php
                    }
                ?>
            </div>
        </div>
        
        <div class="pagination" id="pages" data-page="0" data-total="106" data-epage="5">
            <div class="pagination">
                <a href="./list_<?=$pages->before?>">&lt;</a>
                <?php
                if($pages->total_pages <= 10 ) {
                    for($i= 1;$i<=$pages->total_pages;$i++) {
                        if($i==$pages->current) {
                            echo '<span class="current">'.$i.'</span>';
                        } else {
                            echo '<a href="./list_'.$i.'">'.$i.'</a>';
                        }
                    }
                
                } else if ($pages->total_pages < 17 ) {
                    for($i= 1;$i<= 5;$i++) {
                        if($i==$pages->current) {
                            echo '<span class="current">'.$i.'</span>';
                        } else {
                            echo '<a href="./list_'.$i.'">'.$i.'</a>';
                        }
                    }
                    
                    if($pages->current < 5 ){
                      echo '<span>...</span>';
                    }else if($pages->current >= $pages->total_pages -2) {
                        echo '<span>...</span>';
                    }else if(($pages->current >= 5) && ($pages->current <= 8)) {
                        if( $pages->current+2 > $pages->total_pages -5 ) {
                            for($i = 6;$i<$pages->total_pages -4 ;$i++) {
                                if($i==$pages->current) {
                                    echo '<span class="current">'.$i.'</span>';
                                } else {
                                    echo '<a href="./list_'.$i.'">'.$i.'</a>';
                                }
                            } 
                        }else {
                            for($i = 6;$i<$pages->current+2 ;$i++) {
                                if($i==$pages->current) {
                                    echo '<span class="current">'.$i.'</span>';
                                } else {
                                    echo '<a href="./list_'.$i.'">'.$i.'</a>';
                                }
                            }
                            echo '<span>...</span>'; 
                        }
                    }else if($pages->current >8) {
                        echo '<span>...</span>';
                        for($i = $pages->current -2 ;$i< $pages->total_pages -4;$i++) {
                        if($i==$pages->current) {
                            echo '<span class="current">'.$i.'</span>';
                        } else {
                            echo '<a href="./list_'.$i.'">'.$i.'</a>';
                        }
                        }
                    }
                    
                    for($i = $pages->total_pages -4 ; $i <= $pages->total_pages ; $i++) {
                        if($i==$pages->current) {
                            echo '<span class="current">'.$i.'</span>';
                        } else {
                            echo '<a href="./list_'.$i.'">'.$i.'</a>';
                        }
                    }
                } else if ($pages->total_pages >= 17){
                    for($i= 1;$i<= 5;$i++) {
                        if($i==$pages->current) {
                            echo '<span class="current">'.$i.'</span>';
                        } else {
                            echo '<a href="./list_'.$i.'">'.$i.'</a>';
                        }
                    }
                    
                    if($pages->current >= 5 && $pages->current <= 8 ) {
                        for( $i = 6; $i<= $pages->current+2;$i++) {
                            if($i==$pages->current) {
                                echo '<span class="current">'.$i.'</span>';
                            } else {
                                echo '<a href="./list_'.$i.'">'.$i.'</a>';
                            }
                        }
                    }
                    
                    echo '<span>...</span>';
                    
                    if($pages->current >= 9) {
                        if($pages->current+2 < $pages->total_pages -5) {
                            for( $i = $pages->current -2; $i<= $pages->current+2;$i++) {
                                if($i==$pages->current) {
                                    echo '<span class="current">'.$i.'</span>';
                                } else {
                                    echo '<a href="./list_'.$i.'">'.$i.'</a>';
                                }
                            }
                            echo '<span>...</span>';
                       }else if( $pages->current+2 == $pages->total_pages -5 ) {
                            for( $i = $pages->current -2; $i<= $pages->current+2;$i++) {
                                if($i==$pages->current) {
                                        echo '<span class="current">'.$i.'</span>';
                                    } else {
                                        echo '<a href="./list_'.$i.'">'.$i.'</a>';
                                    }
                            }
                       }else if( $pages->current+2 > $pages->total_pages -5) {
                           for( $i = $pages->current -2; $i<= $pages->total_pages -5;$i++) {
                               if($i==$pages->current) {
                                        echo '<span class="current">'.$i.'</span>';
                                    } else {
                                        echo '<a href="./list_'.$i.'">'.$i.'</a>';
                                    }
                           }
                       }
                    }
                    
                    for($i = $pages->total_pages -4 ; $i <= $pages->total_pages ; $i++) {
                        if($i==$pages->current) {
                            echo '<span class="current">'.$i.'</span>';
                        } else {
                            echo '<a href="./list_'.$i.'">'.$i.'</a>';
                        }
                    }
                } 
                    ?>
                 <a href="./list_<?=$pages->last?>">&gt;</a>
            </div>
        </div>
    </div>
    <div class="monument2_s2">
        <div class="monument2_s2c1 borderside">
            <h4 class="jc_ticon"><?=$this->view->category['category']->name?> 热文推荐</h4>
            <ul>
                <?php
                foreach (Articles::find(array('second_category_id='.$category['category']->id, 'columns'=>'id,name ', 'order'=> 'click_total desc', 'limit'=>8)) as $item) {
                    ?>
                    <li>
                        <a href="../show_<?=$item->id?>" target="_blank" ><?=$item->name?></a>
                    </li>
                    <?php
                }
                ?>
            </ul>
        </div>
        <a href="http://www.ronghedai.com/?user&q=get_share_ajax&alias=drawreg&active_reg=seo_reg" target="_blank"><div class="monument2_s2c2"></div></a>
        <div class="monument2_s2c1 borderside" style="margin-bottom: 20px;">
            <h4 class="jc_ticon"><?=$this->view->category['category']->name?> 最新文章</h4>
            <ul>
                <?php
                foreach (Articles::find(array('second_category_id='.$category['category']->id, 'columns'=>'id,name,first_category_id,second_category_id', 'order'=> 'id desc', 'limit'=>8)) as $item) {
                    ?>
                    <li>
                        <a href="../show_<?=$item->id?>" target="_blank" ><?=$item->name?></a>
                    </li>
                    <?php
                }
                ?>
            </ul>
        </div>
        <div class="monument2_s2c3 clearbb">
            <dl>
                <dt></dt>
                <dd>
                    <h5>立扫二维码</h5>
                    <p>注册即享</p>
                    <p>688现金好礼</p>
                </dd>
            </dl>
        </div>
        <div class="monument2_s2c3 clearbb" id="monument2_s2c3id">
            <dl>
                <dt></dt>
                <dd>
                    <h5>下载APP</h5>
                    <p>融和贷理财app</p>
                    <p>随身财富 触手可及</p>
                </dd>
            </dl>
        </div>
    </div>

</div>

<div class="monument1" id="monument1id">
    
</div>

<div class="monument3 borderside">
    <h4 class="jc_ticon">相关主题</h4>
    <ul class="clearbb" id="monument3c">
        <?php
        foreach (Category::find(array('parent_id=0','columns'=>'name,url')) as $item) {
            ?>
            <li>
                <a href="../<?=$item->url?>/" ><?=$item->name?></a>
            </li>
            <?php
        }
        ?>
    </ul>
</div>