<link href="/zixun/umeditor/themes/default/css/umeditor.css" type="text/css" rel="stylesheet">
<div class="graphs">
    <div class="xs">
        <h3>添加栏目</h3>
        <div class="tab_content">
            <?php
            if (!empty($errorMessage)) {
                ?>
                <div class="alert alert-danger" role="alert">
                    <?=$errorMessage?>
                </div>
                <?php
            }
            ?>
            <div class="tab_pane action">
                <form class="form-horizontal" method="post">
                    <div class="form-group">
                        <label for="focusedinput" class="col-sm-2 control-label">父级目录</label>
                        <div class="col-sm-8">
                            <select name="parent_id">
                                <option value="0">主目录</option>
                                <?php
                                    foreach ($parents as $parent) {
                                        echo '<option value="'.$parent->id.'">'.$parent->name.'</option>';
                                    }
                                ?>
                            </select>

                        </div>
                    </div>
                    <div class="form-group">
                        <label for="focusedinput" class="col-sm-2 control-label">栏目名称</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control1" name="name" id="focusedinput" placeholder="栏目名称">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="focusedinput" class="col-sm-2 control-label">栏目URL</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control1" name="url" id="focusedinput" placeholder="栏目名称">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="focusedinput" class="col-sm-2 control-label">栏目关键字</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control1" name="keyword" id="focusedinput" placeholder="栏目关键字">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="focusedinput" class="col-sm-2 control-label">栏目介绍</label>
                        <div class="col-sm-8">
                            <textarea name="description" class="col-sm-12" placeholder="栏目介绍"></textarea>

                        </div>
                    </div>
                    <div class="form-group">
                        <label for="focusedinput" class="col-sm-2 control-label">内容</label>
                        <div class="col-sm-8">
                            <script type="text/plain" id="container" name="content" style="width:100%;height:240px;"></script>
                        </div>
                    </div>
                    <script type="text/javascript" charset="utf-8" src="/zixun//umeditor/umeditor.config.js"></script>
                    <script type="text/javascript" charset="utf-8" src="/zixun//umeditor/umeditor.min.js"></script>
                    <script type="text/javascript">
                        var ue = UM.getEditor('container');
                    </script>
                    <div class="panel-footer">
                        <div class="row">
                            <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>"
                                   value="<?php echo $this->security->getToken() ?>"/>
                            <div class="col-sm-8 col-sm-offset-2">
                                <button class="btn-success btn">提交</button>
                                <button class="btn-default btn" type="reset">取消</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>