<div class="graphs">
    <div class="xs">
        <h3>添加URL跳转</h3>
        <div class="tab_content">
            <?php
            if (!empty($errorMessage)) {
                ?>
                <div class="alert alert-danger" role="alert">
                    <?=$errorMessage?>
                </div>
                <?php
            }
            ?>
            <div class="tab_pane action">
                <form class="form-horizontal" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label for="focusedinput" class="col-sm-2 control-label">文章URL地址</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control1" name="original_url" id="focusedinput">
                        </div>
                     </div>
                    <div class="form-group">
                        <label for="focusedinput" class="col-sm-2 control-label">广告地址</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control1" name="jump_url">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="focusedinput" class="col-sm-2 control-label">广告图片</label>
                        <div class="col-sm-8">
                            <input type="file" class="form-control1" name="pic_address">
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>"
                                   value="<?php echo $this->security->getToken() ?>"/>
                            <div class="col-sm-8 col-sm-offset-2">
                                <button class="btn-success btn">提交</button>
                                <button class="btn-default btn" type="reset">取消</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>