<div class="graphs">
    <div class="xs">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h2>友情列表</h2>
            </div>
            <div class="panel-body no-padding" style="display: block;">
                <table class="table table-striped">
                    <thead>
                    <tr class="warning">
                        <th>编号</th>
                        <th>名称</th>
                        <th>查看</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                        foreach ($pages->items as $item) {
                    ?>
                    <tr>
                        <td><?=$item->id?></td>
                        <td><?=htmlspecialchars($item->name)?></td>
                        <td><a href="<?=$item->url?>" target="_blank"> 查看</a></td>
                        <td><a href="/zixun/backendrhd/dellinks/<?=$item->id?>"  onclick="return confirm('是否确定删除')">删除</a></td>
                    </tr>
                    <?php
                    }
                    ?>
                    <tr >
                        <td colspan="7" style="text-align: right">
                            <a href="/zixun/backendrhd/linkslist">首页</a>|
                            <a href="/zixun/backendrhd/linkslist/<?= $pages->before; ?>">上一页</a> |
                            <a href="/zixun/backendrhd/linkslist/<?= $pages->next; ?>">下一页</a> |
                            <a href="/zixun/backendrhd/linkslist/<?= $pages->last; ?>">最后一页</a>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>