<div class="graphs">
    <div class="xs">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h2>管理员列表</h2>
            </div>
            <div class="panel-body no-padding" style="display: block;">
                <table class="table table-striped">
                    <thead>
                    <tr class="warning">
                        <th>编号</th>
                        <th>用户名</th>
                        <th>注册IP</th>
                        <th>注册时间</th>
                        <th>最后登录IP</th>
                        <th>最后登录时间</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                        foreach ($userLists as $user) {
                    ?>
                    <tr>
                        <td><?=$user->id?></td>
                        <td><?=$user->username?></td>
                        <td><?=$user->add_ip?></td>
                        <td><?=$user->getRegTime()?></td>
                        <td><?=$user->last_login_ip?></td>
                        <td><?=$user->getLastLoginTime()?></td>
                        <td><a href="../backendrhd/edituser/<?=$user->id?>" >修改</a>|<a href="../backendrhd/deluser/<?=$user->id?>"  onclick="return confirm('是否确定删除')">删除</a></td>
                    </tr>
                    <?php
                    }
                    ?>
                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>