<!doctype html>
<html>
<head>
    <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"/>
     <meta name="format-detection" content="telephone=no">
    <title><?=$result->url_title?></title>

</head>

<body>
<style>
    html,body{margin: 0;padding: 0;height:100%;width:100%;}
    iframe{border: 0;overflow: hidden;}

</style>

<iframe src="<?=$result->original_url;?>" style="width: 100%;height: 100%" id="cons"></iframe>
<div style="position: fixed;bottom: 0;left: 0;width: 100%;">
    <a href="<?=$result->jump_url;?>"><img src="//img.ronghedai.com/<?=$result->pic_address;?>" width="100%" height="60px"></a>
</div>

</body>
</html>
