<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?=$keyword?>-融和贷</title>
    <meta name="keywords" content="<?=$keyword?>" />
    <meta name="description" content="<?=$description?>" />
    <link href="/zixun/css/column.css?v=201656" rel="stylesheet" type="text/css" />
    <link href="http://www.ronghedai.com/dyweb/dythemes/rhd/css/blue/public.css?v=2016912" type="text/css" rel="stylesheet"/>
    <link href="http://www.ronghedai.com/dyweb/dythemes/rhd/css/blue/index.css?v=2016912" type="text/css" rel="stylesheet"/>
    <link href="http://www.ronghedai.com/dyweb/dythemes/rhd/css/blue/new.css?v=2016912" type="text/css" rel="stylesheet"/>
     <link href="http://www.ronghedai.com/dyweb/dythemes/rhd/css/blue/newnew.css?v=2016912" type="text/css" rel="stylesheet"/>
    <script type="text/javascript" src="http://www.ronghedai.com/dyweb/dythemes/rhd/js/jquery-1.8.2.min.js?v=2016419"></script>

</head>

<body>
<div id="header">
	<div class="head">
		<div class="topbar main_w">
			<div class="topbar_left fl">
				<span style="font-size: 14px; line-height: 30px;float: left;width: 224px;">全国统一客服热线：<span>400-182-8687</span></span>				<div class="fl_contnew clearbs">
					<dl class="contnew_l1">
						<dt>手机理财</dt>
						<dd></dd>
					</dl>
					<dl class="contnew_l2">
						<dt>微信理财</dt>
						<dd></dd>
					</dl>
				</div>

			</div>
			<div class="topbar_right fr clearbs">
				<div class="new_barleftt">
										<a href="/?user&amp;q=login">登录 </a>
					<a href="/?user&amp;q=reg">注册</a>
															<a href="/aboutus/index.html">关于我们</a>
					<a href="http://old.ronghedai.com/" style="border: none;padding-right: 0;">访问旧版</a>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="banner">
	<div class="main_w clear">
		<div class="mid fl">
			<img style="margin-top: 11px;" src="/dyweb/dythemes/rhd/images/newimg/newlogo.png" alt="融和贷">
			<a href="/actives/pository/index.html" target="_blank"></a>
		</div>
		<div class="navlist fr">
			<ul class="clear">
							<li class="headna"><a href="/">首页</a></li>
							<li class="headnb"><a href="/rendition/index.html">产品介绍</a></li>
							<li class="headnb"><a href="/invest/index.html">我要理财</a></li>
							<li class="headnb"><a href="/borrow/index.html">我要借款</a></li>
							<li class="headnb headnc"><a href="/mobile/index.html">融和财富</a></li>
							<li class="headnb" style="margin-right: 0px;"><a href="/?user">我的账户</a></li>
						</ul>
		</div>
	</div>
</div>

<div class="monument1">

</div>

<?php echo $this->getContent(); ?>
<div class="new_footer">
    <div class="appearing_side clearf">
        <div class="appearing_at1">
            <dl class="clearf">
                <dd id="foot_ddjiu1">
                    <p class="strongtb">关于融和贷</p>
                    <a href="/aboutus/index.html#box-1" target="_blank">公司介绍</a>
                    <a href="/aboutus/index.html#box-2" target="_blank">品牌荣耀</a>
                    <a href="/aboutus/index.html#box-3" target="_blank">管理团队</a>
                    <a href="/aboutus/index.html#box-4" target="_blank">运营环境</a>
                    <a href="/aboutus/index.html#box-5" target="_blank">融和大事记</a>
                </dd>
                <dd id="foot_ddjiu2">
                    <p class="strongtb">理财安全</p>
                    <a href="/actives/pository/index.html" target="_blank">恒丰存管</a>
                    <a href="/aboutus/index.html#box-6" target="_blank">平台资质</a>
                    <a href="/aboutus/index.html#box-7" target="_blank">安全保障</a>
                    <a href="/tdbz/index.html" target="_blank">DPS风控</a>
                    <a href="/aboutus/index.html#box-8" target="_blank">合规合法</a>
                </dd>
                <dd id="foot_ddjiu3">
                    <p class="strongtb">投资手册</p>
                    <a href="/guidess/index.html" target="_blank">新手指南</a>
                    <a href="/greater/index.html" target="_blank">汇付引导</a>
                    <a href="/aboutus/index.html#box-9" target="_blank">资费说明</a>
                    <a href="/rendition/index.html" target="_blank">产品介绍</a>
                    <a href="/aboutus/index.html#box-10" target="_blank">联系我们</a>
                </dd>
            </dl>
        </div>
        <div class="appearing_at2">
            <ul class="clearf">
                <li class="acv_tv1">
                    <img src="/dyweb/dythemes/rhd/images/gaiban/appew.gif" width="99" height="99">
                    <p>融和贷订阅号</p>
                    <span>微信扫一扫  信息早知道</span>
                </li>
                <li class="acv_tv2">
                    <img src="//img.ronghedai.com/dyweb/dythemes/rhd/images/gaiban/appnew1.gif" width="99" height="99">
                    <p>融和财富APP</p>
                    <span>随身财富  触手可及</span>
                </li>
            </ul>
        </div>
        <div class="appearing_at3">
            <div class="appear_that">
                <h4>400-182-8687</h4>
                <p>全国统一客服热线     早9:00 - 晚21:00</p>
            </div>
            <div class="appear_that2">
                <p>平台投诉建议专线：0551-63717956</p>
                <p style="font-size: 14px;text-align: left;">版权所有©合肥安易贷投资管理有限公司 晥ICP备 14018622号-4</p>
            </div>
        </div>

    </div>
    <div class="appearing_sidec">
        <div class="appearing_side2">

            <div class="f_firends footer_b2">
                <ul class="clearf">
                    <li>友情链接：</li>
                                        <li><a style="text-align: center;" href="http://www.wdzj.com/" target="_blank">网贷之家</a></li>
                                        <li><a style="text-align: center;" href="http://www.p2pchina.com/" target="_blank">网贷中国</a></li>
                                        <li><a style="text-align: center;" href="http://www.p2peye.com/" target="_blank">网贷天眼</a></li>
                                        <li><a style="text-align: center;" href="http://www.wangdaisearch.com" target="_blank">网贷搜索</a></li>
                                        <li><a style="text-align: center;" href="http://www.cnwdjj.com" target="_blank">网贷聚焦</a></li>
                                        <li><a style="text-align: center;" href="http://www.wdtianxia.com/" target="_blank">网贷天下</a></li>
                                        <li><a style="text-align: center;" href="http://www.ronghedai.com/zixun/daikuan/" target="_blank">贷款知识</a></li>
                                        <li><a style="text-align: center;" href="http://www.ronghedai.com/zixun/touzi/" target="_blank">投资理财</a></li>
                                        <li><a style="text-align: center;" href="/yqlj/index.html" target="_blank" rel="external nofollow">更多&gt;&gt;</a></li>
                </ul>
            </div>

            <div class="ont_cuntcction">
                <a style="margin-left: 0;" target="_blank" class="ons23_ttcs" href="http://webscan.360.cn/index/checkwebsite/url/www.ronghedai.com" rel="external nofollow"></a>
                <a target="_blank" class="ons24_ttcs" href="https://ss.knet.cn/verifyseal.dll?sn=e15011934010057405zdte000000&amp;ct=df&amp;a=1&amp;pa=0.11803318278348496" rel="external nofollow"></a>
                <a target="_blank" class="ons25_ttcs" href="https://search.szfw.org/cert/l/CX20150104006258006353" rel="external nofollow"></a>
                <a target="_blank" class="ons26_ttcs" href="http://www.anquan.org/authenticate/cert/?site=www.ronghedai.com&amp;at=business" rel="external nofollow"></a>
                <a target="_blank" class="ons27_ttcs" href="http://www.anquan.org/authenticate/cert/?site=www.ronghedai.com&amp;at=enterprise" rel="external nofollow"></a>
                <a target="_blank" class="ons28_ttcs" href="http://www.beianbeian.com/" rel="external nofollow"></a>
            </div>

        </div>
    </div>
</div>

<script>
    $(function(){
        $('#monument3c li:last').css('margin-right','0px');
        $('.monument1').click(function(){

                       window.location.href="http://www.ronghedai.com/?user&q=get_share_ajax&alias=drawreg&active_reg=seo_reg";

                });
    })
    (function(){
        var bp = document.createElement('script');
        var curProtocol = window.location.protocol.split(':')[0];
        if (curProtocol === 'https') {
            bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
        }
        else {
            bp.src = 'http://push.zhanzhang.baidu.com/push.js';
        }
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(bp, s);
    })();
</script>

<script>

    var _hmt = _hmt || [];

    (function() {

        var hm = document.createElement("script");

        hm.src = "//hm.baidu.com/hm.js?114bdc026b9ff4de87a6efb268dbea76";

        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);

    })();

</script>

</body>
</html>






